plugins {
    id 'java'
    id 'application'
}

group = 'com.gym'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(27)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Material Design 3-inspired Look and Feel
    implementation 'com.formdev:flatlaf:3.5.4'

    implementation 'org.xerial:sqlite-jdbc:3.45.3.0'
}

application {
    // mainClass = 'com.gym.MainApp' // uncomment once MainApp exists
}
